make_test("nixCats_fields", function()
    local nixCats = require('nixCats')
    assert.truthy(nixCats)
    assert.truthy(nixCats.vimPackDir)
    assert.truthy(nixCats.get)
    assert.truthy(nixCats.cats)
    assert.truthy(nixCats.petShop)
    assert.truthy(nixCats.pawsible)
    assert.truthy(nixCats.settings)
    assert.truthy(nixCats.configDir)
    assert.truthy(nixCats.packageBinPath)
    assert.truthy(nixCats.nixCatsPath)
    assert.truthy(nixCats.addGlobals)
end)
