
-- this is a dummy file.

-- nothing will happen if you put stuff in here.

-- it is never called.

-- the actual init.lua is generated by the flake.
-- the generated init.lua just requires whatever folder
-- in the lua directory that you set RCName to.

-- this file is just here so that lua_ls doesnt ask me
-- if I want to configure my workspace as luv
-- every single time.

-- This is here so you can clone the repo to your .config/nvim and unwrap RC and it will still work.
require('myLuaConf')
