make_test("helloNixos", function()
    assert.truthy(nixCats("nixCats_test_names.helloNixos"))
end)
make_test("hello", function()
    assert.truthy(nixCats("nixCats_test_names.hello"))
end)
make_test("modulehello", function()
    assert.truthy(nixCats("nixCats_test_names.modulehello"))
end)
make_test("helloNixosModule", function()
    assert.truthy(nixCats("nixCats_test_names.helloNixosModule"))
end)
