make_test("helloNixos", function()
    assert.True(true)
end)
make_test("hello", function()
    assert.True(true)
end)
make_test("modulehello", function()
    assert.True(true)
end)
make_test("helloNixosModule", function()
    assert.True(true)
end)
