---
permissions:
  contents: write
  pull-requests: write

name: Release Please

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          token: ${{ secrets.PAT }}
